spring:
  cassandra:
    contact-points: ${CASSANDRA_CONTACT_POINTS:localhost}
    port: ${CASSANDRA_PORT:9042}
    keyspace-name: ${CASSANDRA_KEYSPACE_NAME:mykeyspacename}
    local-datacenter: ${CASSANDRA_LOCAL_DATACENTER:datacenter1}
    schema-action: ${CASSANDRA_SCHEMA_ACTION:NONE}
    entity-base-package: com.brewery.web.model
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always
