spring:
  cassandra:
    port: 9042
    contact-points: mycassandra
    keyspace-name: mykeyspacename
    schema-action: CREATE_IF_NOT_EXISTS
    entity-base-package: com.brewery.web.model
    local-datacenter: datacenter1
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always