pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id 'org.podval.tools.scalajs' version '0.9.14'
    }
}

rootProject.name = 'Website_Chat'

include ':scala_js', ':frontend', ':backend'//, ':auth_service:auth_service_backend_ruby'
//        ':auth_service:auth_service_frontend_react'

//project(':auth_service:auth_service_backend_ruby').projectDir = file('auth_service/auth_service_backend_ruby')

//project(':auth_service:auth_service_frontend_react').projectDir =
//        file('auth_service/auth_service_frontend_react')